name: pyb2d3-bp
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - pyb2d3-sandbox-jupyter >= 0.11.0
  - specta >= 0.3.3

  
