name: pyb2d3-bp
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - pyb2d3-sandbox-ipycanvas >= 0.10.0
  - specta >= 0.3.3
  - ipycanvas >= 0.14.2

  